// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Turo.Persistence.CompiledModels
{
    public partial class AppDbContextModel
    {
        public AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("4c84f297-5926-499a-92d9-c2f6e9fdea3e"), entityTypeCount: 11)
        {
        }

        partial void Initialize()
        {
            var agencyLocation = AgencyLocationEntityType.Create(this);
            var booking = BookingEntityType.Create(this);
            var car = CarEntityType.Create(this);
            var carPhoto = CarPhotoEntityType.Create(this);
            var discountOffer = DiscountOfferEntityType.Create(this);
            var individualUser = IndividualUserEntityType.Create(this);
            var maintenanceRecord = MaintenanceRecordEntityType.Create(this);
            var review = ReviewEntityType.Create(this);
            var staff = StaffEntityType.Create(this);
            var user = UserEntityType.Create(this);
            var agency = AgencyEntityType.Create(this, user);

            AgencyLocationEntityType.CreateForeignKey1(agencyLocation, agency);
            BookingEntityType.CreateForeignKey1(booking, car);
            BookingEntityType.CreateForeignKey2(booking, individualUser);
            BookingEntityType.CreateForeignKey3(booking, user);
            CarEntityType.CreateForeignKey1(car, user);
            CarPhotoEntityType.CreateForeignKey1(carPhoto, car);
            DiscountOfferEntityType.CreateForeignKey1(discountOffer, agency);
            MaintenanceRecordEntityType.CreateForeignKey1(maintenanceRecord, car);
            ReviewEntityType.CreateForeignKey1(review, agency);
            ReviewEntityType.CreateForeignKey2(review, car);
            ReviewEntityType.CreateForeignKey3(review, individualUser);
            ReviewEntityType.CreateForeignKey4(review, user);
            StaffEntityType.CreateForeignKey1(staff, agency);

            AgencyLocationEntityType.CreateAnnotations(agencyLocation);
            BookingEntityType.CreateAnnotations(booking);
            CarEntityType.CreateAnnotations(car);
            CarPhotoEntityType.CreateAnnotations(carPhoto);
            DiscountOfferEntityType.CreateAnnotations(discountOffer);
            IndividualUserEntityType.CreateAnnotations(individualUser);
            MaintenanceRecordEntityType.CreateAnnotations(maintenanceRecord);
            ReviewEntityType.CreateAnnotations(review);
            StaffEntityType.CreateAnnotations(staff);
            UserEntityType.CreateAnnotations(user);
            AgencyEntityType.CreateAnnotations(agency);

            AddAnnotation("ProductVersion", "9.0.1");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
